# Header
menu:
  Inicio: /
  Archivo: /archives
  Frecuencias: /frecuencias
rss: /atom.xml

# Content
excerpt_link: Leer artículo
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
# - tagcloud
- archive


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-156538909-1
gauges_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
